server:
  port: 9898
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:contact_info
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
app: 
  messages: 
    contactSaveSucc: Contact Saved
    contactsaveFail: Failed to save contact
    contactDelSucc: Contact Deleted
    contactDelFail: Failed to delete contact   
